### ISSUE TITLE
Using Arduino SRCP stack for own project?

### ISSUE THREAD

**Issue by dcoredump** [mc-b/microSRCP#1]
Hi Marcel,

can we use your SRCP stack for our own project called "ArduRail"? It is hosted on SF and aims to be a MM central with own (interrupt driven) signal generation. Currently it is a library with an optional P50(X) interface. With your SRCP stack it can be a full SRCP central station.

You can contact me at dcoredump@googlemail.com.

Thanks, Holger

**Comment by mc-b** [comment]
No problems, ArduRail uses the same license as microSRCP.

Examples can be found in the wiki (https://github.com/mc-b/microSRCP/wiki/Srcp-protokoll).

For the sources, see https://github.com/mc-b/microSRCP/tree/master/microSRCP/arduino/libraries
-   srcp - for generally SRCP classes and Serial Communications
-   lan - for Ethernet communication

Attention: Serial SRCP Communication only works with RocRail. SRCP is a TCP / IP protocol. See also this thread http://forum.rocrail.net/viewtopic.php?t=5930

**Comment by mc-b** [comment]
closed
